[package]
name = "obsidianbackuper"
version = "0.0.1"
edition = "2024"

[dependencies]
fs_extra = "1.3"
zip = "7.0"
powershell_script = "1.1.0"
frankenstein = { version = "0.46", features = ["client-reqwest"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chrono = "0.4.43"
